### ISSUE TITLE
При видаленні модуля l10n_ua_psbo виникає помилка

### ISSUE THREAD

**Issue by vudomax** [ERP-Ukraine/odoo-addons#51]
При видаленні модуля l10n_ua_psbo виникає помилка:

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 832, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 853, in do_search_read
    request.context)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1069, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5288, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3193, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3239, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5752, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 829, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 936, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 891, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 881, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 425, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/addons/account/models/account_journal_dashboard.py", line 15, in _kanban_dashboard
    self.kanban_dashboard = json.dumps(self.get_journal_dashboard_datas())
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/account/models/account_journal_dashboard.py", line 137, in get_journal_dashboard_datas
    currency = self.currency_id or self.company_id.currency_id
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 829, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 927, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3298, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3228, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3366, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_company.company_registry does not exist
LINE 1: ...ate","res_company"."rml_header1" as "rml_header1","res_compa...
                                                             ^

**Ця помилка лікується видаленням повьязаних модулів l10n_ua_*, після чого обов'язковим оновленням модуля Base.**

**Comment by lem8r** [comment]
Напевно ви скопіювали наші модулі в папку додатків вже після того як була створена база даних.
В цьому випадку вам потрібно один раз запустити сервер Odoo з додатковою опцією ```--init=l10n_ua_psbo``` або вказати цю опцію у файлі налаштувань.  

Документація: http://www.odoo.com/documentation/9.0/reference/cmdline.html

**Comment by lem8r** [comment]
@vudomax не встановлюйте обидва модуля ```l10n_ua_psbo``` і ```l10n_ua_ifrs``` на одну систему. Все рівно буде використовуватись тільки один план рахунків.

**Comment by lem8r** [comment]
Тільки зараз побачив, що йдеться про помилку під час видалення, а не встановлення.
Модулі з планом рахунків немає сенсу видаляти так як вони тільки додають можливість встановити певний план рахунків, який треба обрати в налаштуваннях бух обліку.
